trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022s-hyperv-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022s-sql16d
      provider: hyperv
      configuration: core
      parent: ws2022s
